name=src/main/resources/application.properties
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:${DB_URL}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DB_USER}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASS}}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true

server.port=${PORT:8080}
