spring:
  application:
    name: Conflict-Tracker

  profiles:
    active: prod

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
